packages:
  - packages/*
catalog:
  '@antfu/eslint-config': ^4.1.0
  '@eslint/config-array': ^0.19.1
  '@iconify-json/carbon': ^1.2.5
  '@iconify-json/file-icons': ^1.2.1
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/simple-icons': ^1.2.22
  '@iconify-json/svg-spinners': ^1.2.2
  '@iconify-json/twemoji': ^1.2.2
  '@iconify-json/vscode-icons': ^1.2.11
  '@nuxt/eslint': ^1.0.0
  '@shikijs/langs-precompiled': ^2.2.0
  '@shikijs/transformers': ^2.2.0
  '@types/connect': ^3.4.38
  '@types/ws': ^8.5.14
  '@typescript-eslint/utils': ^8.22.0
  '@unocss/eslint-config': ^65.4.3
  '@unocss/nuxt': ^65.4.3
  '@voxpelli/config-array-find-files': ^1.2.2
  '@vueuse/nuxt': ^12.5.0
  bundle-require: ^5.1.0
  cac: ^6.7.14
  chokidar: ^4.0.3
  debug: ^4.4.0
  esbuild: ^0.24.2
  eslint: ^9.19.0
  fast-glob: ^3.3.3
  find-up: ^7.0.0
  floating-vue: ^5.2.2
  fuse.js: ^7.0.0
  get-port-please: ^3.1.2
  h3: ^1.14.0
  lint-staged: ^15.4.3
  minimatch: ^10.0.1
  mlly: ^1.7.4
  mrmime: ^2.0.0
  nitropack: 2.8.1
  nuxt: ^3.15.4
  nuxt-eslint-auto-explicit-import: ^0.1.1
  open: ^10.1.0
  picocolors: ^1.1.1
  shiki: ^2.2.0
  simple-git-hooks: ^2.11.1
  textmate-grammar-glob: ^0.0.1
  typescript: ^5.7.3
  unbuild: ^3.3.1
  vitest: ^3.0.4
  vue-tsc: ^2.2.0
  ws: ^8.18.0
